source "https://cdn.cocoapods.org/"

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

platform :ios, '11.0'

use_frameworks!

target 'Extensions_Example' do
  # pod 'Extensions', :path => '../'
  pod 'Extensions/Rx', :path => '../'
  pod 'Extensions/MDC', :path => '../'

# playground "Extensions.playground" do
#    pod 'Extensions', :path => '../'
# end
# support_iboutlets!

  target 'Extensions_Tests' do
    inherit! :search_paths

    
  end
end
